name: iTidez
main: me.itidez.plugins.icreative.Core
version: 1.0B1
softdepend: [WorldGuard, WorldEdit, MultiInv, MultiInv, Multiverse-Inventories]
dev-url: http://dev.bukkit.org/server-mods/limited-creative/
commands:
    iCreative:
        description: "iCreative: GameMode-Switch, Creative-Regions, Config"
        aliases: lc
        usage: /<command> - displays LimitedCreative-Help
    /region:
        description: "iCreative-Region-Command: configure creative regions"
        aliases: lcregion
        usage: /<command> info|flag [<world>#]<region> - set/get region options
permissions:
    icreative.config:
        description: Allows enabling/disabling of config options ingame
        default: op
    icreative.regions:
        description: Allows usage of the //region commands
        default: op
    icreative.regions.bypass:
        description: Ignores the force of a gamemode, when region optional is disabled
        default: false
    icreative.switch_gamemode:
        description: Allows switching of own game mode to creative/adventure and back
        default: op
    icreative.switch_gamemode.backonly:
        description: Allows switching of own game mode to default of the not world he is in, but not back
        default: false
    icreative.switch_gamemode.survival:
        description: Allows switching of own game mode to survival, but not to creative/adventure
        default: false
    icreative.switch_gamemode.creative:
        description: Allows switching of own game mode to creative, but not to survival/adventure
        default: false
    iimitedcreative.switch_gamemode.adventure:
        description: Allows switching of own game mode to adventure, but not to creative/survival
        default: false
    icreative.switch_gamemode.other:
        description: Allows switching of other users game mode
        default: op
    icreative.keepinventory:
        description: Allows bypassing the inventory separation
        default: false
    icreative.nolimit.drop:
        description: Allows bypassing the "do not drop anything"-limitation
        default: false
    icreative.nolimit.pickup:
        description: Allows bypassing the "do not pickup anything"-limitation
        default: false
    icreative.nolimit.chest:
        description: Allows bypassing the "do not open a chest"-limitation
        default: false
    icreative.nolimit.sign:
        description: Allows bypassing the "do not interact with signs"-limitation
        default: false
    icreative.nolimit.button:
        description: Allows bypassing the "do not interact with buttons"-limitation
        default: false
    icreative.nolimit.lever:
        description: Allows bypassing the "do not interact with levers"-limitation
        default: false
    icreative.nolimit.pvp:
        description: Allows bypassing the "no pvp"-limitation
        default: false
    icreative.nolimit.mob_damage:
        description: Allows bypassing the "no dealing damage to creatures"-limitation
        default: false
    icreative.nolimit.use:
        description: Allows bypassing the "block place/item use"-limitation
        default: false
    icreative.nolimit.break:
        description: Allows bypassing the "block break"-limitation
        default: false
    icreative.cmdblock.all:
        description: Allowy bypassting the "command block"-limitation
        default: op
